### ISSUE TITLE
Support resource tags/metadata for provisioned resources

### ISSUE THREAD

**Issue by jbpratt** [RedHatQE/teflo_openstack_client_plugin#9]
It would be useful to be able to tag resources or create metadata with a specific value in order to help track machines related to a specific scenario

**Comment by rujutashinde** [comment]
Could you please list out what you would run using openstack client cli  to acheive this, for us to get a better understanding

**Comment by jbpratt** [comment]
I believe tags should be able to be added to a server with the `--tag` command but I haven't tested this for confirmation
```
❯ openstack server create --help | grep tag
                               [--nic <net-id=net-uuid,port-id=port-uuid,v4-fixed-ip=ip-addr,v6-fixed-ip=ip-addr,tag=tag,auto,none>]
                               [--min <count>] [--max <count>] [--tag <tag>]
                        tag=<tag>: device metadata tag (optional),
  --nic <net-id=net-uuid,port-id=port-uuid,v4-fixed-ip=ip-addr,v6-fixed-ip=ip-addr,tag=tag,auto,none>
                        tag: interface metadata tag (optional) (supported by
  --tag <tag>           Tags for the server. Specify multiple times to add
                        multiple tags. (supported by --os-compute-api-version
```

**Comment by jbpratt** [comment]
For existing servers, tags can be set with `openstack server set --tag KEY=VALUE <name>`

**Comment by rujutashinde** [comment]
Jira ticket CCITCARBON-308 has been created for this issue. Url : https://projects.engineering.redhat.com/browse/CCITCARBON-308

**Comment by JunqiZhang0** [comment]
no longer needed
